### ISSUE TITLE
why not use 307 or 308 redirect?

### ISSUE THREAD

**Issue by ryanmeador** [battlejj/express-force-ssl#16]
Is there a reason you use a 301 redirect for GETs and a 403 for everything else instead of just redirecting all methods using a 307 or a 308?  It seems to me that it would be a better experience for the user.

http://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection

**Comment by battlejj** [comment]
I am not entirely opposed having a discussion on the use of a 308 status code. The 307 status code is only for temporary redirection and this library is intended to force SSL so should deal specifically with permanent redirection when used. 

As for status code 308, my understanding is that this is still and experimental RFC and I don't see implementing it as a sound strategy until it is finalized. Even after finalization of this RFC, there will need to be a discussion of whether this is a sound strategy because one could argue that allowing 308 redirects for POST/PUT/DELETE requests encourages misuse. 

Needing to use a 308 for this could give a false impression to a developer that their entire application is behind SSL, when in fact data could be POSTed via HTTP (maybe in an AJAX call) and just 308 redirected to the correct endpoint. The developer may not discover this vulnerability as quickly as they would if a 403 error was returned as the library currently does.

I am open to hearing other opinions on the matter though.

**Comment by ryanmeador** [comment]
Hi, thanks for the reply.  I think I came across as more confrontational than I intended, I apologize.  I found your library when I was looking for something that would let me redirect users of my webapp to HTTPS, since I just added an SSL cert yesterday.  The app is almost entirely a REST API, and to support older clients (that don't know to use HTTPS), I'd want exactly the transparent redirects that you're talking about in relation to the 308.  Your point is a good one -- for many use cases, you'd want the fail-fast behavior to alert the developer to the bug.  Perhaps it could be configurable?

If I do decide to implement redirection, I may fork your project.  If I made the status code changes as a config option, would you be amenable to a pull request?

**Comment by battlejj** [comment]
@ryanmeador you didn't come across as confrontational at all, you raised a valid issue. I think adding the ability to have 308 redirects as an opt-in feature has value. Do you see this as a global setting? Or do you see this as something that should be configurable on a route-by-route basis?

My first thought would be that it would be a global setting, because developers probably either want 308 redirects for all routes or for none, but I am would like your input on the matter since this is a feature that you are interested in.

**Comment by battlejj** [comment]
Hey @ryanmeador have an open issue I am investigating that I've merged this into, going to close out this issue but happy to further discuss in #19
